### ISSUE TITLE
Clarification of behavior for "needs" and "name" tags in pipeline stage docs

### ISSUE THREAD

**Issue by mitruly** [go-vela/docs-old#214]
**Background**
When reading the example provided in the [pipeline stages `needs` documentation](https://github.com/go-vela/docs/blob/master/content/concepts/pipeline/stages/needs.md), it is not obvious that the stage name is used for the `needs` value rather than the stage key.

**Explanation**
The following pipeline works, which is described in the documentation:
```
stages:
   foo:
      steps:
         - name: step-1
            image: golang
            ...
   bar:
      needs: foo
      steps:
         - name: step-2
            image: golang
            ...
```

However, the following will _not_ have the stage dependency:
```
stages:
   foo:
      name: "Foo stage"
      steps:
         - name: step-1
            image: golang
            ...
   bar:
      needs: foo
      steps:
         - name: step-2
            image: golang
            ...
```

This will only work if the `stages.bar.needs` value is set to`"Foo stage"`.

It would be nice if the stage key (e.g. `foo`) could be used, rather than the override name that's intended for UI formatting.
