### ISSUE TITLE
Ansible plugin `lint-skip` parameters

### ISSUE THREAD

**Issue by lashomb** [go-vela/docs-old#380]
The example docs show `lint-skip` being used with id numbers, that I couldn't find anywhere, even after looking at the source. I tried using names, ie: `no-changed-when`, and that worked. Unsure if numeric ids are still available for this and I've yet to discover them, or if names should be used instead.

```
    parameters:
      action: lint
      playbook: "ansible/playbook.yml"
      lint_skip:
        - no-changed-when
```
